cd src

msbuild "wolf.sln" /m /p:PlatformToolset="v141_xp" /p:Configuration="%BUILD_CONFIGURATION%"

IF ERRORLEVEL 1 GOTO ERROR

cd %APPVEYOR_BUILD_FOLDER%/src/%BUILD_CONFIGURATION%
7z a "%APPVEYOR_BUILD_FOLDER%/ETe-Win32-%APPVEYOR_REPO_TAG_NAME%-%BUILD_CONFIGURATION%.7z" ETe.exe
cd %APPVEYOR_BUILD_FOLDER%/src/ded/%BUILD_CONFIGURATION%
7z a "%APPVEYOR_BUILD_FOLDER%/ETe-Win32-%APPVEYOR_REPO_TAG_NAME%-%BUILD_CONFIGURATION%.7z" ETe-ded.exe
cd %APPVEYOR_BUILD_FOLDER%
7z a "ETe-Win32-%APPVEYOR_REPO_TAG_NAME%-%BUILD_CONFIGURATION%.7z" docs\*

IF ERRORLEVEL 1 GOTO ERROR

GOTO END

:ERROR

echo "Building ETe failed"

:END
